service: go-serverless-todo
frameworkVersion: '4.14.4'

provider:
  name: aws
  runtime: provided.al2            # ✅ Go теперь через кастомный runtime
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  architecture: x86_64
  memorySize: 256
  timeout: 10
  logRetentionInDays: 7

  environment:
    TODOS_TABLE: ${self:service}-${opt:stage, 'dev'}-todos

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.TODOS_TABLE}

package:
  artifact: bin/handler.zip       # ZIP должен содержать файл bootstrap

functions:
  getTodo:
    handler: bootstrap            # ✅ bootstrap — это entry point для provided.al2
    memorySize: 256
    timeout: 5
    description: "Get all TODOs"
    environment:
      STAGE: ${opt:stage, 'dev'}
    events:
      - http:
          path: todos
          method: get
          cors: true
          authorizer: aws_iam
    maximumRetryAttempts: 1

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
